/**
 * api/routes.js
 * Express Router — all REST endpoints for the Health Staff Scheduler.
 *
 * All routes follow the same error convention:
 *   success → 200 (or 201) with JSON body
 *   not found → 404 { error: "..." }
 *   bad request → 400 { error: "..." }
 *   server error → 500 { error: "..." }
 */

'use strict';

const express = require('express');
const router = express.Router();

const { store } = require('../data/schema');
const { runOrchestrator } = require('../agents/orchestrator');

// ---------------------------------------------------------------------------
// Urgency sort order helper (critical → high → medium → low)
// ---------------------------------------------------------------------------
const URGENCY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 };
const BURNOUT_ORDER = { red: 0, yellow: 1, green: 2 };

// ===========================================================================
// Health check
// ===========================================================================

/**
 * GET /api/health
 * Simple liveness check. Returns the timestamp of the last orchestrator run.
 */
router.get('/health', (req, res) => {
  res.json({ status: 'ok', lastRun: store.lastRun });
});

// ===========================================================================
// Orchestrator
// ===========================================================================

/**
 * POST /api/orchestrator/run
 * Triggers the full 4-agent pipeline and returns the digest.
 * This is the primary demo endpoint — expect it to take 10–30 seconds.
 */
router.post('/orchestrator/run', async (req, res) => {
  try {
    const digest = await runOrchestrator();
    res.json(digest);
  } catch (err) {
    console.error('[POST /orchestrator/run]', err);
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Staff
// ===========================================================================

// ---------------------------------------------------------------------------
// Burnout recovery helper
// Returns hours a staff member has been off-shift (0 if currently on shift).
// ---------------------------------------------------------------------------
function hoursOffShift(start24, end24) {
  if (!start24 || !end24) return 0;
  const toMins = (t) => { const [h, m] = t.split(':').map(Number); return h * 60 + (m || 0); };
  const now     = new Date();
  const nowMins = now.getHours() * 60 + now.getMinutes();
  const s = toMins(start24);
  const e = toMins(end24);
  if (e > s) {
    // Normal shift (e.g. 07:00–19:00) — off when clock has passed end
    if (nowMins < e) return 0;
    return (nowMins - e) / 60;
  }
  // Overnight shift (e.g. 19:00–07:00) — on shift when now >= start OR now < end
  if (nowMins >= s || nowMins < e) return 0;
  return (nowMins - e) / 60;
}

function applyBurnoutRecovery(risk, start24, end24) {
  if (!risk || risk === 'green') return risk;
  const off = hoursOffShift(start24, end24);
  if (off >= 10) return 'green';
  if (off >= 6 && risk === 'red') return 'yellow';
  return risk;
}

/**
 * GET /api/staff
 * Returns all staff members with burnout risk adjusted for time off-shift.
 * Red → yellow after 6 hrs off; any risk → green after 10 hrs off.
 */
router.get('/staff', (req, res) => {
  try {
    // Index today's schedule by staffId for quick lookup
    const schedMap = {};
    (store.todaySchedule || []).forEach((e) => {
      if (e.staffId) schedMap[e.staffId] = e;
    });

    const staff = store.staff.map((member) => {
      const sched = schedMap[member.id];
      if (!sched || !member.burnoutRisk) return member;
      const recovered = applyBurnoutRecovery(member.burnoutRisk, sched.shiftStart, sched.shiftEnd);
      if (recovered === member.burnoutRisk) return member;
      return { ...member, burnoutRisk: recovered };
    });

    res.json(staff);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/staff/:id
 * Returns a single staff member combined with their latest burnout score.
 */
router.get('/staff/:id', (req, res) => {
  try {
    const member = store.staff.find((s) => s.id === req.params.id);
    if (!member) {
      return res.status(404).json({ error: `Staff member ${req.params.id} not found.` });
    }

    // Attach the latest burnout score if the monitor has run
    const burnoutScore = store.burnoutScores.find((b) => b.staffId === req.params.id) || null;

    res.json({ ...member, burnoutScore });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Forecasts
// ===========================================================================

/**
 * GET /api/forecasts
 * Returns all demand forecasts generated by Agent 1.
 */
router.get('/forecasts', (req, res) => {
  try {
    res.json(store.forecasts);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Schedule
// ===========================================================================

/**
 * GET /api/schedule
 * Returns the optimised schedule generated by Agent 2.
 */
router.get('/schedule', (req, res) => {
  try {
    res.json(store.schedule);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Burnout
// ===========================================================================

/**
 * GET /api/burnout
 * Returns burnout scores sorted red → yellow → green (highest risk first).
 */
router.get('/burnout', (req, res) => {
  try {
    const sorted = [...store.burnoutScores].sort(
      (a, b) =>
        (BURNOUT_ORDER[a.burnoutRisk] ?? 3) - (BURNOUT_ORDER[b.burnoutRisk] ?? 3)
    );
    res.json(sorted);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Interventions
// ===========================================================================

/**
 * GET /api/interventions
 * Returns all intervention recommendations sorted critical → high → medium → low.
 */
router.get('/interventions', (req, res) => {
  try {
    const sorted = [...store.interventions].sort(
      (a, b) =>
        (URGENCY_ORDER[a.urgency] ?? 4) - (URGENCY_ORDER[b.urgency] ?? 4)
    );
    res.json(sorted);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/interventions/pending
 * Returns only interventions that have NOT yet been approved, sorted by urgency.
 */
router.get('/interventions/pending', (req, res) => {
  try {
    const pending = store.interventions
      .filter((i) => !i.approved)
      .sort((a, b) => (URGENCY_ORDER[a.urgency] ?? 4) - (URGENCY_ORDER[b.urgency] ?? 4));
    res.json(pending);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/interventions/:id/approve
 * Marks an intervention as approved (charge nurse one-click approval).
 * In production this would also trigger the downstream scheduling action.
 */
router.post('/interventions/:id/approve', (req, res) => {
  try {
    const intervention = store.interventions.find((i) => i.id === req.params.id);
    if (!intervention) {
      return res.status(404).json({ error: `Intervention ${req.params.id} not found.` });
    }
    if (intervention.approved) {
      return res.status(400).json({ error: 'Intervention has already been approved.' });
    }

    intervention.approved = true;
    res.json({ message: 'Intervention approved.', intervention });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Today's Schedule
// ===========================================================================

/**
 * GET /api/today-schedule
 * Returns every staff member's shift entry for today with hours worked.
 * Optional query param: ?unit=ICU-1
 */
router.get('/today-schedule', (req, res) => {
  try {
    let entries = store.todaySchedule;
    if (req.query.unit) {
      entries = entries.filter((e) => e.unit === req.query.unit);
    }
    res.json(entries);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/today-schedule/:staffId
 * Returns today's schedule entry for a specific staff member.
 */
router.get('/today-schedule/:staffId', (req, res) => {
  try {
    const entry = store.todaySchedule.find((e) => e.staffId === req.params.staffId);
    if (!entry) {
      return res.status(404).json({ error: `No schedule entry found for staff ${req.params.staffId}` });
    }
    res.json(entry);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Patients
// ===========================================================================

/**
 * GET /api/patients
 * Returns all patients. Optional query param: ?unit=MedSurg-3
 */
router.get('/patients', (req, res) => {
  try {
    let patients = store.patients;
    if (req.query.unit) {
      patients = patients.filter((p) => p.unit === req.query.unit);
    }
    res.json(patients);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/patients/:id
 * Returns a single patient with their appointments for today.
 */
router.get('/patients/:id', (req, res) => {
  try {
    const patient = store.patients.find((p) => p.id === req.params.id);
    if (!patient) {
      return res.status(404).json({ error: `Patient ${req.params.id} not found.` });
    }
    const appointments = store.appointments.filter((a) => a.patientId === req.params.id);
    res.json({ ...patient, appointments });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Appointments
// ===========================================================================

/**
 * GET /api/appointments
 * Returns all appointments for today.
 * Optional query params: ?unit=ICU-1  ?status=scheduled  ?staffId=<id>
 */
router.get('/appointments', (req, res) => {
  try {
    let appts = store.appointments;
    if (req.query.unit)    appts = appts.filter((a) => a.unit === req.query.unit);
    if (req.query.status)  appts = appts.filter((a) => a.status === req.query.status);
    if (req.query.staffId) appts = appts.filter((a) => a.assignedStaffId === req.query.staffId);
    res.json(appts);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * PATCH /api/appointments/:id/status
 * Body: { status: 'completed' | 'in_progress' | 'cancelled' }
 * Updates the status of an appointment.
 */
router.patch('/appointments/:id/status', (req, res) => {
  try {
    const appt = store.appointments.find((a) => a.id === req.params.id);
    if (!appt) {
      return res.status(404).json({ error: `Appointment ${req.params.id} not found.` });
    }
    const validStatuses = ['scheduled', 'in_progress', 'completed', 'cancelled'];
    const { status } = req.body;
    if (!validStatuses.includes(status)) {
      return res.status(400).json({ error: `status must be one of: ${validStatuses.join(', ')}` });
    }
    appt.status = status;
    res.json({ message: 'Appointment status updated.', appointment: appt });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Auth / Users
// ===========================================================================

/**
 * POST /api/auth/login
 * Body: { loginId, password }
 * Simple credential check — returns user record (minus password) on success.
 * NOTE: No JWT/sessions here — demo only. Add proper auth middleware in production.
 */
router.post('/auth/login', (req, res) => {
  try {
    const { loginId, password } = req.body;
    if (!loginId || !password) {
      return res.status(400).json({ error: 'loginId and password are required.' });
    }

    const user = store.users.find((u) => u.loginId === loginId);
    if (!user || user.password !== password) {
      return res.status(401).json({ error: 'Invalid credentials.' });
    }

    // Return user info without the password field
    const { password: _pw, ...safeUser } = user;
    res.json({ message: 'Login successful.', user: safeUser });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/users
 * Returns all user accounts (passwords omitted).
 */
router.get('/users', (_req, res) => {
  try {
    const safeUsers = store.users.map(({ password: _pw, ...u }) => u);
    res.json(safeUsers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Wellness Check-In
// ===========================================================================

/**
 * POST /api/checkin/:staffId
 * Body: { wellnessScore: 1-5 }
 * Updates a staff member's self-reported wellness score.
 * In production, this feeds the burnout model in real time via a Firestore
 * trigger or a queued background job.
 */
router.post('/checkin/:staffId', (req, res) => {
  try {
    const member = store.staff.find((s) => s.id === req.params.staffId);
    if (!member) {
      return res.status(404).json({ error: `Staff member ${req.params.staffId} not found.` });
    }

    const { wellnessScore } = req.body;
    if (wellnessScore === undefined || wellnessScore === null) {
      return res.status(400).json({ error: 'wellnessScore is required in the request body.' });
    }

    const score = Number(wellnessScore);
    if (!Number.isInteger(score) || score < 1 || score > 5) {
      return res
        .status(400)
        .json({ error: 'wellnessScore must be an integer between 1 and 5.' });
    }

    member.wellnessScore = score;

    console.log(`[Checkin] ${member.name} submitted wellnessScore: ${score}`);
    res.json({ message: 'Wellness check-in recorded.', staff: member });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Timeline
// ===========================================================================

/**
 * GET /api/timeline?date=YYYY-MM-DD
 * Returns shift entries for the requested date, shaped for the timeline view.
 * Uses todaySchedule for today; falls back to historical store.shifts for past dates.
 */
router.get('/timeline', (req, res) => {
  try {
    const SHIFT_TIMES = {
      day:     { start: '07:00', end: '19:00' },
      evening: { start: '15:00', end: '03:00' },
      night:   { start: '19:00', end: '07:00' },
    };

    const today   = new Date().toISOString().split('T')[0];
    const dateStr = req.query.date || today;

    if (dateStr === today) {
      return res.json(
        store.todaySchedule.map((e) => ({
          staffId:    e.staffId,
          staffName:  e.staffName,
          role:       e.role,
          unit:       e.unit,
          shiftStart: e.shiftStart,
          shiftEnd:   e.shiftEnd,
          shiftType:  e.shiftType,
          status:     e.status,
        }))
      );
    }

    // Future date — use store.futureSchedule
    const reqDate  = new Date(dateStr);
    const todayDate = new Date(today);
    if (reqDate > todayDate) {
      const entries = store.futureSchedule
        .filter((e) => e.date === dateStr)
        .map((e) => ({
          staffId:    e.staffId,
          staffName:  e.staffName,
          role:       e.role,
          unit:       e.unit,
          shiftStart: e.shiftStart,
          shiftEnd:   e.shiftEnd,
          shiftType:  e.shiftType,
          status:     e.status,
        }));
      return res.json(entries);
    }

    // Historical date — use store.shifts
    const staffMap = {};
    store.staff.forEach((s) => { staffMap[s.id] = s; });

    const entries = store.shifts
      .filter((s) => s.date && s.date.startsWith(dateStr))
      .map((s) => {
        const member = staffMap[s.staffId] || {};
        const times  = SHIFT_TIMES[s.type] || SHIFT_TIMES.day;
        return {
          staffId:    s.staffId,
          staffName:  member.name  || 'Unknown',
          role:       member.role  || '—',
          unit:       s.unit,
          shiftStart: times.start,
          shiftEnd:   times.end,
          shiftType:  s.type,
          status:     'completed',
        };
      });

    res.json(entries);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Future Schedule (next 14 days)
// ===========================================================================

/**
 * GET /api/future-schedule?date=YYYY-MM-DD
 * Returns all future schedule entries for the given date.
 */
router.get('/future-schedule', (req, res) => {
  try {
    const { date } = req.query;
    const entries = date
      ? store.futureSchedule.filter((e) => e.date === date)
      : store.futureSchedule;
    res.json(entries);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/future-schedule
 * Body: { staffId, date, shiftType }
 * Adds a new schedule entry for a future date.
 */
router.post('/future-schedule', (req, res) => {
  try {
    const { createScheduleEntry } = require('../data/schema');
    const SHIFT_TIMES = {
      day:     { start: '07:00', end: '19:00' },
      evening: { start: '15:00', end: '03:00' },
      night:   { start: '19:00', end: '07:00' },
    };

    const { staffId, date, shiftType = 'day' } = req.body;
    if (!staffId || !date) {
      return res.status(400).json({ error: 'staffId and date are required.' });
    }

    const member = store.staff.find((s) => s.id === staffId);
    if (!member) return res.status(404).json({ error: 'Staff member not found.' });

    const times = SHIFT_TIMES[shiftType] || SHIFT_TIMES.day;
    const entry = createScheduleEntry({
      staffId,
      staffName:  member.name,
      role:       member.role,
      unit:       member.unit,
      date,
      shiftType,
      shiftStart: times.start,
      shiftEnd:   times.end,
      status:     'scheduled',
    });

    store.futureSchedule.push(entry);
    res.status(201).json(entry);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * PATCH /api/future-schedule/:id
 * Body: { shiftType?, status? }
 * Updates an existing future schedule entry.
 */
router.patch('/future-schedule/:id', (req, res) => {
  try {
    const SHIFT_TIMES = {
      day:     { start: '07:00', end: '19:00' },
      evening: { start: '15:00', end: '03:00' },
      night:   { start: '19:00', end: '07:00' },
    };

    const entry = store.futureSchedule.find((e) => e.id === req.params.id);
    if (!entry) return res.status(404).json({ error: 'Schedule entry not found.' });

    const { shiftType, status } = req.body;
    if (shiftType && ['day', 'evening', 'night'].includes(shiftType)) {
      const times = SHIFT_TIMES[shiftType];
      entry.shiftType  = shiftType;
      entry.shiftStart = times.start;
      entry.shiftEnd   = times.end;
    }
    if (status && ['scheduled', 'absent'].includes(status)) {
      entry.status = status;
    }

    res.json(entry);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * DELETE /api/future-schedule/:id
 * Removes a future schedule entry.
 */
router.delete('/future-schedule/:id', (req, res) => {
  try {
    const idx = store.futureSchedule.findIndex((e) => e.id === req.params.id);
    if (idx === -1) return res.status(404).json({ error: 'Schedule entry not found.' });
    store.futureSchedule.splice(idx, 1);
    res.json({ message: 'Entry removed.' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Pending Patients
// ===========================================================================

/**
 * GET /api/pending-patients
 * Returns all pending patients. Optional ?unit=ICU-1 and ?scheduled=false
 */
router.get('/pending-patients', (req, res) => {
  try {
    let patients = store.pendingPatients;
    if (req.query.unit) patients = patients.filter((p) => p.unit === req.query.unit);
    if (req.query.scheduled !== undefined) {
      const want = req.query.scheduled === 'true';
      patients = patients.filter((p) => p.scheduled === want);
    }
    res.json(patients);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * PATCH /api/pending-patients/:id
 * Body: { assignedStaffId?, scheduledDate?, scheduledTime?, scheduled? }
 */
router.patch('/pending-patients/:id', (req, res) => {
  try {
    const patient = store.pendingPatients.find((p) => p.id === req.params.id);
    if (!patient) return res.status(404).json({ error: 'Pending patient not found.' });

    const { assignedStaffId, scheduledDate, scheduledTime, scheduled } = req.body;
    if (assignedStaffId !== undefined) patient.assignedStaffId = assignedStaffId;
    if (scheduledDate   !== undefined) patient.scheduledDate   = scheduledDate;
    if (scheduledTime   !== undefined) patient.scheduledTime   = scheduledTime;
    if (scheduled       !== undefined) patient.scheduled       = scheduled;

    res.json(patient);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// AI-assisted future schedule optimisation
// ===========================================================================

/**
 * POST /api/optimize-future?date=YYYY-MM-DD
 * Runs the schedule optimiser against the draft future schedule and pending
 * patients for the given date, returning AI suggestions.
 */
router.post('/optimize-future', async (req, res) => {
  try {
    const { runFutureOptimizer } = require('../agents/scheduleOptimizer');
    const date = req.query.date || req.body.date;
    if (!date) return res.status(400).json({ error: 'date query param required.' });

    const entries  = store.futureSchedule.filter((e) => e.date === date);
    const pending  = store.pendingPatients.filter((p) => !p.scheduled && p.dateNeededBy >= date);

    const result = await runFutureOptimizer(date, entries, pending, store.staff);

    // Apply any schedule suggestions back to the store
    if (Array.isArray(result.scheduleUpdates)) {
      result.scheduleUpdates.forEach((upd) => {
        const entry = store.futureSchedule.find((e) => e.id === upd.id);
        if (entry && upd.shiftType) {
          const SHIFT_TIMES = {
            day: { start: '07:00', end: '19:00' },
            evening: { start: '15:00', end: '03:00' },
            night: { start: '19:00', end: '07:00' },
          };
          const times = SHIFT_TIMES[upd.shiftType];
          if (times) {
            entry.shiftType  = upd.shiftType;
            entry.shiftStart = times.start;
            entry.shiftEnd   = times.end;
          }
        }
      });
    }

    res.json(result);
  } catch (err) {
    console.error('[POST /optimize-future]', err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
