/**
 * api/routes.js
 * Express Router — all REST endpoints for the Health Staff Scheduler.
 *
 * All routes follow the same error convention:
 *   success → 200 (or 201) with JSON body
 *   not found → 404 { error: "..." }
 *   bad request → 400 { error: "..." }
 *   server error → 500 { error: "..." }
 */

'use strict';

const express = require('express');
const router = express.Router();

const { store } = require('../data/schema');
const { runOrchestrator } = require('../agents/orchestrator');

// ---------------------------------------------------------------------------
// Urgency sort order helper (critical → high → medium → low)
// ---------------------------------------------------------------------------
const URGENCY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 };
const BURNOUT_ORDER = { red: 0, yellow: 1, green: 2 };

// ===========================================================================
// Health check
// ===========================================================================

/**
 * GET /api/health
 * Simple liveness check. Returns the timestamp of the last orchestrator run.
 */
router.get('/health', (req, res) => {
  res.json({ status: 'ok', lastRun: store.lastRun });
});

// ===========================================================================
// Orchestrator
// ===========================================================================

/**
 * POST /api/orchestrator/run
 * Triggers the full 4-agent pipeline and returns the digest.
 * This is the primary demo endpoint — expect it to take 10–30 seconds.
 */
router.post('/orchestrator/run', async (req, res) => {
  try {
    const digest = await runOrchestrator();
    res.json(digest);
  } catch (err) {
    console.error('[POST /orchestrator/run]', err);
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Staff
// ===========================================================================

/**
 * GET /api/staff
 * Returns all staff members.
 */
router.get('/staff', (req, res) => {
  try {
    res.json(store.staff);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/staff/:id
 * Returns a single staff member combined with their latest burnout score.
 */
router.get('/staff/:id', (req, res) => {
  try {
    const member = store.staff.find((s) => s.id === req.params.id);
    if (!member) {
      return res.status(404).json({ error: `Staff member ${req.params.id} not found.` });
    }

    // Attach the latest burnout score if the monitor has run
    const burnoutScore = store.burnoutScores.find((b) => b.staffId === req.params.id) || null;

    res.json({ ...member, burnoutScore });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Forecasts
// ===========================================================================

/**
 * GET /api/forecasts
 * Returns all demand forecasts generated by Agent 1.
 */
router.get('/forecasts', (req, res) => {
  try {
    res.json(store.forecasts);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Schedule
// ===========================================================================

/**
 * GET /api/schedule
 * Returns the optimised schedule generated by Agent 2.
 */
router.get('/schedule', (req, res) => {
  try {
    res.json(store.schedule);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Burnout
// ===========================================================================

/**
 * GET /api/burnout
 * Returns burnout scores sorted red → yellow → green (highest risk first).
 */
router.get('/burnout', (req, res) => {
  try {
    const sorted = [...store.burnoutScores].sort(
      (a, b) =>
        (BURNOUT_ORDER[a.burnoutRisk] ?? 3) - (BURNOUT_ORDER[b.burnoutRisk] ?? 3)
    );
    res.json(sorted);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Interventions
// ===========================================================================

/**
 * GET /api/interventions
 * Returns all intervention recommendations sorted critical → high → medium → low.
 */
router.get('/interventions', (req, res) => {
  try {
    const sorted = [...store.interventions].sort(
      (a, b) =>
        (URGENCY_ORDER[a.urgency] ?? 4) - (URGENCY_ORDER[b.urgency] ?? 4)
    );
    res.json(sorted);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/interventions/pending
 * Returns only interventions that have NOT yet been approved, sorted by urgency.
 */
router.get('/interventions/pending', (req, res) => {
  try {
    const pending = store.interventions
      .filter((i) => !i.approved)
      .sort((a, b) => (URGENCY_ORDER[a.urgency] ?? 4) - (URGENCY_ORDER[b.urgency] ?? 4));
    res.json(pending);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/interventions/:id/approve
 * Marks an intervention as approved (charge nurse one-click approval).
 * In production this would also trigger the downstream scheduling action.
 */
router.post('/interventions/:id/approve', (req, res) => {
  try {
    const intervention = store.interventions.find((i) => i.id === req.params.id);
    if (!intervention) {
      return res.status(404).json({ error: `Intervention ${req.params.id} not found.` });
    }
    if (intervention.approved) {
      return res.status(400).json({ error: 'Intervention has already been approved.' });
    }

    intervention.approved = true;
    res.json({ message: 'Intervention approved.', intervention });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Today's Schedule
// ===========================================================================

/**
 * GET /api/today-schedule
 * Returns every staff member's shift entry for today with hours worked.
 * Optional query param: ?unit=ICU-1
 */
router.get('/today-schedule', (req, res) => {
  try {
    let entries = store.todaySchedule;
    if (req.query.unit) {
      entries = entries.filter((e) => e.unit === req.query.unit);
    }
    res.json(entries);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/today-schedule/:staffId
 * Returns today's schedule entry for a specific staff member.
 */
router.get('/today-schedule/:staffId', (req, res) => {
  try {
    const entry = store.todaySchedule.find((e) => e.staffId === req.params.staffId);
    if (!entry) {
      return res.status(404).json({ error: `No schedule entry found for staff ${req.params.staffId}` });
    }
    res.json(entry);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Patients
// ===========================================================================

/**
 * GET /api/patients
 * Returns all patients. Optional query param: ?unit=MedSurg-3
 */
router.get('/patients', (req, res) => {
  try {
    let patients = store.patients;
    if (req.query.unit) {
      patients = patients.filter((p) => p.unit === req.query.unit);
    }
    res.json(patients);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/patients/:id
 * Returns a single patient with their appointments for today.
 */
router.get('/patients/:id', (req, res) => {
  try {
    const patient = store.patients.find((p) => p.id === req.params.id);
    if (!patient) {
      return res.status(404).json({ error: `Patient ${req.params.id} not found.` });
    }
    const appointments = store.appointments.filter((a) => a.patientId === req.params.id);
    res.json({ ...patient, appointments });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Appointments
// ===========================================================================

/**
 * GET /api/appointments
 * Returns all appointments for today.
 * Optional query params: ?unit=ICU-1  ?status=scheduled  ?staffId=<id>
 */
router.get('/appointments', (req, res) => {
  try {
    let appts = store.appointments;
    if (req.query.unit)    appts = appts.filter((a) => a.unit === req.query.unit);
    if (req.query.status)  appts = appts.filter((a) => a.status === req.query.status);
    if (req.query.staffId) appts = appts.filter((a) => a.assignedStaffId === req.query.staffId);
    res.json(appts);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * PATCH /api/appointments/:id/status
 * Body: { status: 'completed' | 'in_progress' | 'cancelled' }
 * Updates the status of an appointment.
 */
router.patch('/appointments/:id/status', (req, res) => {
  try {
    const appt = store.appointments.find((a) => a.id === req.params.id);
    if (!appt) {
      return res.status(404).json({ error: `Appointment ${req.params.id} not found.` });
    }
    const validStatuses = ['scheduled', 'in_progress', 'completed', 'cancelled'];
    const { status } = req.body;
    if (!validStatuses.includes(status)) {
      return res.status(400).json({ error: `status must be one of: ${validStatuses.join(', ')}` });
    }
    appt.status = status;
    res.json({ message: 'Appointment status updated.', appointment: appt });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Auth / Users
// ===========================================================================

/**
 * POST /api/auth/login
 * Body: { loginId, password }
 * Simple credential check — returns user record (minus password) on success.
 * NOTE: No JWT/sessions here — demo only. Add proper auth middleware in production.
 */
router.post('/auth/login', (req, res) => {
  try {
    const { loginId, password } = req.body;
    if (!loginId || !password) {
      return res.status(400).json({ error: 'loginId and password are required.' });
    }

    const user = store.users.find((u) => u.loginId === loginId);
    if (!user || user.password !== password) {
      return res.status(401).json({ error: 'Invalid credentials.' });
    }

    // Return user info without the password field
    const { password: _pw, ...safeUser } = user;
    res.json({ message: 'Login successful.', user: safeUser });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/users
 * Returns all user accounts (passwords omitted).
 */
router.get('/users', (_req, res) => {
  try {
    const safeUsers = store.users.map(({ password: _pw, ...u }) => u);
    res.json(safeUsers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Wellness Check-In
// ===========================================================================

/**
 * POST /api/checkin/:staffId
 * Body: { wellnessScore: 1-5 }
 * Updates a staff member's self-reported wellness score.
 * In production, this feeds the burnout model in real time via a Firestore
 * trigger or a queued background job.
 */
router.post('/checkin/:staffId', (req, res) => {
  try {
    const member = store.staff.find((s) => s.id === req.params.staffId);
    if (!member) {
      return res.status(404).json({ error: `Staff member ${req.params.staffId} not found.` });
    }

    const { wellnessScore } = req.body;
    if (wellnessScore === undefined || wellnessScore === null) {
      return res.status(400).json({ error: 'wellnessScore is required in the request body.' });
    }

    const score = Number(wellnessScore);
    if (!Number.isInteger(score) || score < 1 || score > 5) {
      return res
        .status(400)
        .json({ error: 'wellnessScore must be an integer between 1 and 5.' });
    }

    member.wellnessScore = score;

    console.log(`[Checkin] ${member.name} submitted wellnessScore: ${score}`);
    res.json({ message: 'Wellness check-in recorded.', staff: member });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===========================================================================
// Timeline
// ===========================================================================

/**
 * GET /api/timeline?date=YYYY-MM-DD
 * Returns shift entries for the requested date, shaped for the timeline view.
 * Uses todaySchedule for today; falls back to historical store.shifts for past dates.
 */
router.get('/timeline', (req, res) => {
  try {
    const SHIFT_TIMES = {
      day:     { start: '07:00', end: '19:00' },
      evening: { start: '15:00', end: '03:00' },
      night:   { start: '19:00', end: '07:00' },
    };

    const today   = new Date().toISOString().split('T')[0];
    const dateStr = req.query.date || today;

    if (dateStr === today) {
      return res.json(
        store.todaySchedule.map((e) => ({
          staffId:    e.staffId,
          staffName:  e.staffName,
          role:       e.role,
          unit:       e.unit,
          shiftStart: e.shiftStart,
          shiftEnd:   e.shiftEnd,
          shiftType:  e.shiftType,
          status:     e.status,
        }))
      );
    }

    // Historical date — use store.shifts
    const staffMap = {};
    store.staff.forEach((s) => { staffMap[s.id] = s; });

    const entries = store.shifts
      .filter((s) => s.date && s.date.startsWith(dateStr))
      .map((s) => {
        const member = staffMap[s.staffId] || {};
        const times  = SHIFT_TIMES[s.type] || SHIFT_TIMES.day;
        return {
          staffId:    s.staffId,
          staffName:  member.name  || 'Unknown',
          role:       member.role  || '—',
          unit:       s.unit,
          shiftStart: times.start,
          shiftEnd:   times.end,
          shiftType:  s.type,
          status:     'completed',
        };
      });

    res.json(entries);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
